tracking_video_path: "demo_vid/853889-hd_1920_1080_25fps.mp4"
reid_video_path: "demo_vid/853889-hd_1920_1080_25fps.mp4"
model_path: "yolov8s.pt"
deepsort:
  max_age: 30
  n_init: 3
  nn_budget: 100
similarity:
  min: 0.90
  max: 0.65


logging:
  verbose: false
